services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 6886:1883
      - 9001:9001
      
  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: admin
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   ports: 
  #     - 4321:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  config:
  data:
  log:
  postgres-data:
    driver: local



